export const GitHubLight = {
  "code.hljs": { padding: "3px 5px" },
  hljs: { color: "#24292e", background: "#ffffff" },
  "hljs-doctag": { color: "#d73a49" },
  "hljs-keyword": { color: "#d73a49" },
  "hljs-template-tag": { color: "#d73a49" },
  "hljs-template-variable": { color: "#d73a49" },
  "hljs-type": { color: "#d73a49" },
  "hljs-variable.language_": { color: "#d73a49" },
  "hljs-title": { color: "#6f42c1" },
  "hljs-title.class_": { color: "#6f42c1" },
  "hljs-title.class_.inherited__": { color: "#6f42c1" },
  "hljs-title.function_": { color: "#6f42c1" },
  "hljs-attr": { color: "#005cc5" },
  "hljs-attribute": { color: "#005cc5" },
  "hljs-literal": { color: "#005cc5" },
  "hljs-meta": { color: "#005cc5" },
  "hljs-number": { color: "#005cc5" },
  "hljs-operator": { color: "#005cc5" },
  "hljs-variable": { color: "#005cc5" },
  "hljs-selector-attr": { color: "#005cc5" },
  "hljs-selector-class": { color: "#005cc5" },
  "hljs-selector-id": { color: "#005cc5" },
  "hljs-regexp": { color: "#032f62" },
  "hljs-string": { color: "#032f62" },
  "hljs-built_in": { color: "#e36209" },
  "hljs-symbol": { color: "#e36209" },
  "hljs-comment": { color: "#6a737d" },
  "hljs-code": { color: "#6a737d" },
  "hljs-formula": { color: "#6a737d" },
  "hljs-name": { color: "#22863a" },
  "hljs-quote": { color: "#22863a" },
  "hljs-selector-tag": { color: "#22863a" },
  "hljs-selector-pseudo": { color: "#22863a" },
  "hljs-subst": { color: "#24292e" },
  "hljs-section": { color: "#005cc5", "font-weight": "bold" },
  "hljs-bullet": { color: "#735c0f" },
  "hljs-emphasis": { color: "#24292e", "font-style": "italic" },
  "hljs-strong": { color: "#24292e", "font-weight": "bold" },
  "hljs-addition": { color: "#22863a", "background-color": "#f0fff4" },
  "hljs-deletion": { color: "#b31d28", "background-color": "#ffeef0" },
  "hljs-char.escape_": {},
  "hljs-link": {},
  "hljs-params": {},
  "hljs-property": {},
  "hljs-punctuation": {},
  "hljs-tag": {},
};

export const GitHubDark = {
  "code.hljs": { padding: "3px 5px" },
  hljs: { color: "#c9d1d9", background: "#0d1117" },
  "hljs-doctag": { color: "#ff7b72" },
  "hljs-keyword": { color: "#ff7b72" },
  "hljs-template-tag": { color: "#ff7b72" },
  "hljs-template-variable": { color: "#ff7b72" },
  "hljs-type": { color: "#ff7b72" },
  "hljs-variable.language_": { color: "#ff7b72" },
  "hljs-title": { color: "#d2a8ff" },
  "hljs-title.class_": { color: "#d2a8ff" },
  "hljs-title.class_.inherited__": { color: "#d2a8ff" },
  "hljs-title.function_": { color: "#d2a8ff" },
  "hljs-attr": { color: "#79c0ff" },
  "hljs-attribute": { color: "#79c0ff" },
  "hljs-literal": { color: "#79c0ff" },
  "hljs-meta": { color: "#79c0ff" },
  "hljs-number": { color: "#79c0ff" },
  "hljs-operator": { color: "#79c0ff" },
  "hljs-variable": { color: "#79c0ff" },
  "hljs-selector-attr": { color: "#79c0ff" },
  "hljs-selector-class": { color: "#79c0ff" },
  "hljs-selector-id": { color: "#79c0ff" },
  "hljs-regexp": { color: "#a5d6ff" },
  "hljs-string": { color: "#a5d6ff" },
  "hljs-built_in": { color: "#ffa657" },
  "hljs-symbol": { color: "#ffa657" },
  "hljs-comment": { color: "#8b949e" },
  "hljs-code": { color: "#8b949e" },
  "hljs-formula": { color: "#8b949e" },
  "hljs-name": { color: "#7ee787" },
  "hljs-quote": { color: "#7ee787" },
  "hljs-selector-tag": { color: "#7ee787" },
  "hljs-selector-pseudo": { color: "#7ee787" },
  "hljs-subst": { color: "#c9d1d9" },
  "hljs-section": { color: "#1f6feb", "font-weight": "bold" },
  "hljs-bullet": { color: "#f2cc60" },
  "hljs-emphasis": { color: "#c9d1d9", "font-style": "italic" },
  "hljs-strong": { color: "#c9d1d9", "font-weight": "bold" },
  "hljs-addition": { color: "#aff5b4", "background-color": "#033a16" },
  "hljs-deletion": { color: "#ffdcd7", "background-color": "#67060c" },
  "hljs-char.escape_": {},
  "hljs-link": {},
  "hljs-params": {},
  "hljs-property": {},
  "hljs-punctuation": {},
  "hljs-tag": {},
};
