// Generated by dts-bundle-generator v9.5.1

import { DiffFile, DiffHighlighter } from '@git-diff-view/core';
import { CSSProperties, ForwardedRef, ReactNode } from 'react';
import { Ref, UseSelectorWithStore } from 'reactivity-store';

export declare enum DiffModeEnum {
	SplitGitHub = 1,
	SplitGitLab = 2,
	Split = 3,
	Unified = 4
}
export declare const DiffViewContext: import("react").Context<{
	useDiffContext: UseSelectorWithStore<{
		id: Ref<string>;
		mode: Ref<DiffModeEnum>;
		enableWrap: Ref<boolean>;
		enableAddWidget: Ref<boolean>;
		enableHighlight: Ref<boolean>;
		fontSize: Ref<number>;
		renderWidgetLine: Ref<DiffViewProps<any>["renderWidgetLine"]>;
		extendData: Ref<DiffViewProps<any>["extendData"]>;
		renderExtendLine: Ref<DiffViewProps<any>["renderExtendLine"]>;
		onAddWidgetClick: {
			current: DiffViewProps<any>["onAddWidgetClick"];
		};
	}>;
}>;
export declare const useDiffViewContext: () => {
	useDiffContext: UseSelectorWithStore<{
		id: Ref<string>;
		mode: Ref<DiffModeEnum>;
		enableWrap: Ref<boolean>;
		enableAddWidget: Ref<boolean>;
		enableHighlight: Ref<boolean>;
		fontSize: Ref<number>;
		renderWidgetLine: Ref<DiffViewProps<any>["renderWidgetLine"]>;
		extendData: Ref<DiffViewProps<any>["extendData"]>;
		renderExtendLine: Ref<DiffViewProps<any>["renderExtendLine"]>;
		onAddWidgetClick: {
			current: DiffViewProps<any>["onAddWidgetClick"];
		};
	}>;
};
export declare const diffFontSizeName = "--diff-font-size--";
export declare enum SplitSide {
	old = 1,
	new = 2
}
export type DiffViewProps<T> = {
	data?: {
		oldFile?: {
			fileName?: string | null;
			fileLang?: string | null;
			content?: string | null;
		};
		newFile?: {
			fileName?: string | null;
			fileLang?: string | null;
			content?: string | null;
		};
		hunks: string[];
	};
	extendData?: {
		oldFile?: Record<string, {
			data: T;
		}>;
		newFile?: Record<string, {
			data: T;
		}>;
	};
	diffFile?: DiffFile;
	className?: string;
	style?: CSSProperties;
	/**
	 * provide a custom highlighter
	 * eg: lowlight, refractor, starry-night, shiki
	 */
	registerHighlighter?: Omit<DiffHighlighter, "getHighlighterEngine">;
	diffViewMode?: DiffModeEnum;
	diffViewWrap?: boolean;
	diffViewFontSize?: number;
	diffViewHighlight?: boolean;
	diffViewAddWidget?: boolean;
	renderWidgetLine?: ({ diffFile, side, lineNumber, onClose, }: {
		lineNumber: number;
		side: SplitSide;
		diffFile: DiffFile;
		onClose: () => void;
	}) => ReactNode;
	renderExtendLine?: ({ diffFile, side, data, lineNumber, onUpdate, }: {
		lineNumber: number;
		side: SplitSide;
		data: T;
		diffFile: DiffFile;
		onUpdate: () => void;
	}) => ReactNode;
	onAddWidgetClick?: (lineNumber: number, side: SplitSide) => void;
};
export declare const DiffView: (<T>(props: DiffViewProps<T> & {
	ref?: ForwardedRef<{
		getDiffFileInstance: () => DiffFile;
	}>;
}) => ReactNode) & {
	displayName?: string;
};
export declare const version: string;
export * from "@git-diff-view/core";

export {
	DiffFile,
	DiffHighlighter,
};

export {};
