// Generated by dts-bundle-generator v9.5.1

declare class TextMeasure {
	
	measure(text: string, font?: {
		fontFamily?: string;
		fontStyle?: string;
		fontSize?: string;
	}): number;
}
export declare const getTextMeasureInstance: () => TextMeasure;

export {};
